# Generated by Django 4.2.5 on 2023-10-05 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transaction_sender_alter_transaction_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('reference_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_receipt', models.ImageField(upload_to='coin_transaction_receipts/')),
                ('date_in_receipt', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('is_denied', models.BooleanField(default=False)),
                ('requestee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
