# Generated by Django 4.2.5 on 2023-10-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_remove_cointransaction_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransaction',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
