# Generated by Django 4.2.5 on 2023-10-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_cointransaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='points_to_add',
            field=models.FloatField(default=0.0),
        ),
    ]
