# Generated by Django 4.2.5 on 2023-10-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_userprofileinfo_points_to_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='points_to_add',
            new_name='points_to_give',
        ),
    ]
