# Generated by Django 4.2.5 on 2023-10-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='rfid_value',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
